### ISSUE TITLE
dae,xacro,urdf files for gazebo?

### ISSUE THREAD

**Issue by hakuturu583** [WHILL/ros_whill#22]
Hi, I want to try ros_whill by gazebo, but I found that there is no gazebo related files for whill.
Is there any files which related to gazebo is public?

**Comment by aquahika** [comment]
There is only a bare link model with a boxy body at this time: https://github.com/WHILL/ros_whill/blob/melodic-devel/xacro/modelc.xacro. 

Unfortunately slicker and cooler one does not exist yet.
Your commission or any suggestions for Gazebo models are really welcome!
