### ISSUE TITLE
How can I control whill with external joy controller?

### ISSUE THREAD

**Issue by vachmas** [WHILL/ros_whill#23]
I would like to use external joy like logitech joystick to control the movement of the whill via ros package.
How can I do this?

Thank in advance.

**Comment by seiya0412** [comment]
Thank you for using WHILL Model CR and ros_whill package!

ros_whill node [subscribes](https://github.com/WHILL/ros_whill#controllerjoy-sensor_msgsjoy) `<ros_whill's node-name>/controller/joy` topic whose type is [sensor_msgs/Joy](http://docs.ros.org/melodic/api/sensor_msgs/html/msg/Joy.html).

remap your joystick node's output to `<ros_whill's node-name>/controller/joy`, and it should work.

Note: axes[0] is longitudinal direction, and axes[1] is lateral direction.
