### ISSUE TITLE
complete documentation

### ISSUE THREAD

**Issue by yani-rl-ai** [WHILL/ros_whill#31]
hi @aquahika, thank you for providing us whill repository on github, i am new user. i also new in ROS. 
do you have complete documentation from the beginning to setup whill for ROS ? 
this readme on this github is quite short

**Comment by s-katsu** [comment]
Thank you for your comment.

How to use ros_whill is easy, 
so there is no documentation on how to use ros_whill other than README.

You need only 2 steps, serial port setting and launch.

https://github.com/WHILL/ros_whill#serialport-setting-for-ros_whilllaunch
https://github.com/WHILL/ros_whill#launch-with-model

If you just do this, you can communicate with rostopic.
The topic also uses a generic message as much as possible, so you can find out how to use a generic ROS topic.
