### ISSUE TITLE
how to update the firmware?

### ISSUE THREAD

**Issue by yani-rl-ai** [WHILL/ros_whill#32]
HI @aquahika  
i want to update the firmware for my whill
can you provide the information about that?

**Comment by s-katsu** [comment]
@ROSNovice 
Thank you for your comment.

Please contact your WHILL sales representative for firmware updates.
Or you can contact us from here.
https://whill.inc/jp/whill-contact#content-whill-private-customer

The specific update procedure itself will be communicated to you by our sales staff.

It will be in Japanese, but the same inquiry is answered here.

https://github.com/WHILL/Model_CR_Technical_Support/issues/28

**Comment by s-katsu** [comment]
I think you have not any comment, I'll colse this issue.
Could you reopen If you need some discussion.
