### ISSUE TITLE
whillをgazeboで動かしたいです

### ISSUE THREAD

**Issue by mayo233** [WHILL/ros_whill#33]
https://github.com/WHILL/ros_whill/blob/melodic-devel/xacro/modelc.xacro.を起動してwhillをgazeboで動かしたいです．
どのようにコマンドを入力すれば良いでしょうか？

**Comment by s-katsu** [comment]
https://github.com/WHILL/Model_CR_Technical_Support/issues/31
で回答した通りです。
こちらもCloseさせていただきます。
