### ISSUE TITLE
Does this repository plan to support ROS2?

### ISSUE THREAD

**Issue by Hidenaga41** [WHILL/ros_whill#34]
I would like to use ROS2 for research purposes, but this repository does not seem to have been updated recently.
Please let me know if there are any plans to support ROS2.
Thank you.

**Comment by s-katsu** [comment]
We don’t have a plan to support ROS2 officially.

But there is a unofficial repository.

This will be developed by volunteer members.

[https://github.com/whill-labs/ros2_whill](https://github.com/whill-labs/ros2_whill)

As a precaution, we haven’t maintenance the repository ros2_whill long time, 

only support crystal-devel.

So the source code does not suite with later ROS2 distoribution.

Sorry.

**Comment by Hidenaga41** [comment]
Thank you for your reply.
I will have a look at the repository.
